version: '3'
services:
  postgres:
    image: postgres:15.4
    environment:
      POSTGRES_DB: inventario_db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventario-net

  inventario:
    image: inventario-1.0.0
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      APP_URL: http://localhost:8082
      SERVER_PORT: 8082
      direccion.compras: http://localhost:8081
      direccion.catalogo: http://localhost:8084/api
      logging.level.root: INFO
    ports:
      - 8082:8082
    networks:
      - inventario-net

networks:
  inventario-net:

volumes:
  postgres_data:

